/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wbsdev.telas;

import br.com.wbsdev.entity.Usuario;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Willian
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
    }
    public TelaPrincipal(Usuario usu){
         initComponents();
         lblUsu.setText(usu.getNome());
         setData();
         bloquearFuncao(usu);
         this.setExtendedState(MAXIMIZED_BOTH);
         
        
    }
    
  
    
    public void setData(){
        Date data = new Date();
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        String dataAtual = f.format(data.getTime());
        lblData.setText(dataAtual);
    }
  
   public void bloquearFuncao(Usuario usu){
       if(usu.getTipo().equals("colaborador")){
           itmUsu.setEnabled(false);
           itmServ.setEnabled(false);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        lblUsu = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuCad = new javax.swing.JMenu();
        itmCli = new javax.swing.JMenuItem();
        itmUsu = new javax.swing.JMenuItem();
        itmOs = new javax.swing.JMenuItem();
        jMenuRelat = new javax.swing.JMenu();
        itmServ = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        itmSobre = new javax.swing.JMenuItem();
        jMenuOpc = new javax.swing.JMenu();
        itmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para controle de OS");
        setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        lblUsu.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsu.setForeground(new java.awt.Color(153, 0, 0));
        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsu.setText("Usuário");

        lblData.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 255));
        lblData.setText("Data");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbsdev/icones/x.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jMenu.setBackground(new java.awt.Color(51, 51, 51));
        jMenu.setForeground(new java.awt.Color(51, 51, 51));

        jMenuCad.setText("Cadastro");

        itmCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        itmCli.setText("Clientes");
        jMenuCad.add(itmCli);

        itmUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        itmUsu.setText("Usuário");
        itmUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmUsuActionPerformed(evt);
            }
        });
        jMenuCad.add(itmUsu);

        itmOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        itmOs.setText("OS");
        jMenuCad.add(itmOs);

        jMenu.add(jMenuCad);

        jMenuRelat.setText("Relatório");

        itmServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        itmServ.setText("Serviços");
        jMenuRelat.add(itmServ);

        jMenu.add(jMenuRelat);

        jMenuAjuda.setText("Ajuda");

        itmSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        itmSobre.setText("Sobre");
        itmSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(itmSobre);

        jMenu.add(jMenuAjuda);

        jMenuOpc.setText("Opções");

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        jMenuOpc.add(itmSair);

        jMenu.add(jMenuOpc);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblData)
                            .addComponent(lblUsu))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblUsu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblData)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel4)
                        .addGap(95, 95, 95)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1022, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        int resultado = JOptionPane.showConfirmDialog(null, "Deseja sair da aplicação?","Atenção!",JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(resultado == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSobreActionPerformed
        TelaSobre telaSobre = new TelaSobre();
         telaSobre.setVisible(true);
       
       
    }//GEN-LAST:event_itmSobreActionPerformed

    private void itmUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUsuActionPerformed
        TelaCadUsu telaCadUsu = null;
        try {
            telaCadUsu = new TelaCadUsu();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaCadUsu.setVisible(true);
        jdpPrincipal.add(telaCadUsu);
    }//GEN-LAST:event_itmUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCli;
    private javax.swing.JMenuItem itmOs;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmServ;
    private javax.swing.JMenuItem itmSobre;
    private javax.swing.JMenuItem itmUsu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuCad;
    private javax.swing.JMenu jMenuOpc;
    private javax.swing.JMenu jMenuRelat;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblUsu;
    // End of variables declaration//GEN-END:variables
}
