/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wbsdev.telas;

import br.com.wbsdev.DAO.UsuarioDao;
import br.com.wbsdev.entity.Usuario;
import br.com.wbsdev.modeloTabela.ModeloTabelaUsuario;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Willian
 */
public class TelaCadUsu extends javax.swing.JInternalFrame {
   private UsuarioDao usuDao = new UsuarioDao();
   
    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadUsu() throws SQLException{
        initComponents();
        txtIdUsu.setEnabled(false);
        rdVazio.setVisible(false);
       preencherTabela();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpRdBtn = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdUsu = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        rdAdmin = new javax.swing.JRadioButton();
        rdColab = new javax.swing.JRadioButton();
        pwdSenha = new javax.swing.JPasswordField();
        rdVazio = new javax.swing.JRadioButton();
        jfmtFone = new javax.swing.JFormattedTextField();
        btnCad = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de usuários");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbsdev/icones/iconfinder_user-id_285641 (1).png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Telefone");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Login");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Senha");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Tipo");

        gpRdBtn.add(rdAdmin);
        rdAdmin.setText("Administrador");

        gpRdBtn.add(rdColab);
        rdColab.setText("Colaborador");

        gpRdBtn.add(rdVazio);
        rdVazio.setText("jRadioButton1");

        try {
            jfmtFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdVazio)
                .addGap(147, 147, 147))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNome)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rdAdmin)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(rdColab)
                                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jfmtFone, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfmtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAdmin)
                    .addComponent(rdColab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdVazio))
        );

        btnCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbsdev/icones/adicionar-usuario.png"))); // NOI18N
        btnCad.setToolTipText("Cadastrar ");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbsdev/icones/do-utilizador.png"))); // NOI18N
        btnEdit.setToolTipText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbsdev/icones/deletar-usuario.png"))); // NOI18N
        btnDelete.setToolTipText("Deletar");

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wbsdev/icones/procurar.png"))); // NOI18N
        btnPesquisa.setToolTipText("Pesquisar");

        jtbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPesquisa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdit)))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCad)
                            .addComponent(btnEdit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete)
                            .addComponent(btnPesquisa)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limparCampos(){
        txtIdUsu.setText("");
        txtNome.setText("");
        jfmtFone.setText("");
        txtLogin.setText("");
        pwdSenha.setText("");
        rdVazio.setSelected(true);
    }
    
    public void preencherTabela() throws SQLException{
        String [] colunas = {"Id","Nome","Telefone","Login","Senha","Tipo"};
        ArrayList linhas = usuDao.buscarTodosParaPreencherTabela();
        
        ModeloTabelaUsuario mu = new ModeloTabelaUsuario(linhas, colunas);
        jtbUsuarios.setModel(mu);
        
         jtbUsuarios.getColumnModel().getColumn(0).setPreferredWidth(70);
          jtbUsuarios.getColumnModel().getColumn(0).setResizable(false);
          jtbUsuarios.getColumnModel().getColumn(1).setPreferredWidth(200);
          jtbUsuarios.getColumnModel().getColumn(1).setResizable(false);
          jtbUsuarios.getColumnModel().getColumn(2).setPreferredWidth(120);
          jtbUsuarios.getColumnModel().getColumn(2).setResizable(false);
          jtbUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
          jtbUsuarios.getColumnModel().getColumn(3).setResizable(false);
          jtbUsuarios.getColumnModel().getColumn(4).setPreferredWidth(100);
          jtbUsuarios.getColumnModel().getColumn(4).setResizable(false);
          jtbUsuarios.getColumnModel().getColumn(5).setPreferredWidth(100);
          jtbUsuarios.getColumnModel().getColumn(5).setResizable(false);
          
          jtbUsuarios.getTableHeader().setReorderingAllowed(false);
          jtbUsuarios.setAutoResizeMode(0);
          jtbUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    
    }
    
    public void carregarDadosDaTabelaParaTela(){
        if(jtbUsuarios.getSelectedRow() != -1){
            txtIdUsu.setText(jtbUsuarios.getValueAt(jtbUsuarios.getSelectedRow(), 0).toString());
            txtNome.setText(jtbUsuarios.getValueAt(jtbUsuarios.getSelectedRow(), 1).toString());
            jfmtFone.setText(retiraMascaraTelefone(jtbUsuarios.getValueAt(jtbUsuarios.getSelectedRow(), 2).toString()));
            txtLogin.setText(jtbUsuarios.getValueAt(jtbUsuarios.getSelectedRow(), 3).toString());
            pwdSenha.setText(jtbUsuarios.getValueAt(jtbUsuarios.getSelectedRow(), 4).toString());
            String tipo = jtbUsuarios.getValueAt(jtbUsuarios.getSelectedRow(), 5).toString();
            if(tipo.equals("Administrador")){
                rdAdmin.setSelected(true);
            }else if(tipo.equals("Colaborador")){
                rdColab.setSelected(true);
            }
        }
    }
    
    public String retiraMascaraTelefone(String telefone){
        StringBuilder builder = new StringBuilder(telefone);
        
        for(int i = 0; i < builder.length(); i++){
            if(builder.charAt(i) == '('|| builder.charAt(i) == ')' || builder.charAt(i) ==  '-' ){
                    builder.deleteCharAt(i);
            }
        }
        
        return telefone = builder.toString();
    }

    
    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        Usuario usu = new Usuario();
        usu.setNome(txtNome.getText());
        usu.setTelefone(jfmtFone.getText());
        usu.setLogin(txtLogin.getText());
        usu.setSenha(pwdSenha.getText());
        if(rdAdmin.isSelected()){
            usu.setTipo(rdAdmin.getText());
        }else if(rdColab.isSelected()){
            usu.setTipo(rdColab.getText());
        }
       Boolean statusCad = usuDao.cadastrar(usu);
       if(statusCad){
           JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
           limparCampos();
       }else{
           JOptionPane.showMessageDialog(null, "Algo deu errado! Tente cadastrar o usuário novamente.");
       }
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      carregarDadosDaTabelaParaTela();
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.ButtonGroup gpRdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jfmtFone;
    private javax.swing.JTable jtbUsuarios;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JRadioButton rdAdmin;
    private javax.swing.JRadioButton rdColab;
    private javax.swing.JRadioButton rdVazio;
    private javax.swing.JTextField txtIdUsu;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
